<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            ['name' => 'Leche evaporada', 'description' => 'Leche evaporada de diferentes marcas y tamaños', 'unit_id' => 7, 'active' => true],
            ['name' => 'Leche fresca', 'description' => 'Leche pasteurizada en botellas o bolsas', 'unit_id' => 1, 'active' => true],
            ['name' => 'Yogures', 'description' => 'Yogures bebibles y en vaso', 'unit_id' => 1, 'active' => true],
            ['name' => 'Quesos', 'description' => 'Variedades de queso fresco y madurado', 'unit_id' => 2, 'active' => true],
            ['name' => 'Mantequilla y margarina', 'description' => 'Untables lácteos', 'unit_id' => 2, 'active' => true],
            ['name' => 'Huevos', 'description' => 'Huevos de gallina por unidad o docena', 'unit_id' => 9, 'active' => true],
            ['name' => 'Gaseosas', 'description' => 'Bebidas carbonatadas de diversas marcas', 'unit_id' => 1, 'active' => true],
            ['name' => 'Aguas minerales', 'description' => 'Agua con o sin gas', 'unit_id' => 1, 'active' => true],
            ['name' => 'Jugos naturales', 'description' => 'Jugos y néctares embotellados', 'unit_id' => 1, 'active' => true],
            ['name' => 'Bebidas isotónicas', 'description' => 'Bebidas energizantes y deportivas', 'unit_id' => 1, 'active' => true],
            ['name' => 'Cerveza', 'description' => 'Cerveza nacional e importada', 'unit_id' => 1, 'active' => true],
            ['name' => 'Vinos', 'description' => 'Vinos tintos, blancos y rosados', 'unit_id' => 1, 'active' => true],
            ['name' => 'Licores', 'description' => 'Ron, whisky, vodka y otros destilados', 'unit_id' => 1, 'active' => true],
            ['name' => 'Arroz', 'description' => 'Variedades de arroz en bolsas y sacos', 'unit_id' => 2, 'active' => true],
            ['name' => 'Azúcar', 'description' => 'Azúcar blanca y rubia', 'unit_id' => 2, 'active' => true],
            ['name' => 'Fideos', 'description' => 'Fideos y pastas secas de trigo', 'unit_id' => 2, 'active' => true],
            ['name' => 'Aceites', 'description' => 'Aceite vegetal y de oliva', 'unit_id' => 1, 'active' => true],
            ['name' => 'Sal', 'description' => 'Sal yodada o marina', 'unit_id' => 2, 'active' => true],
            ['name' => 'Café', 'description' => 'Café molido e instantáneo', 'unit_id' => 2, 'active' => true],
            ['name' => 'Té e infusiones', 'description' => 'Variedades de té y hierbas', 'unit_id' => 8, 'active' => true],
            ['name' => 'Galletas dulces', 'description' => 'Variedades de galletas dulces', 'unit_id' => 8, 'active' => true],
            ['name' => 'Galletas saladas', 'description' => 'Galletas de soda y snacks salados', 'unit_id' => 8, 'active' => true],
            ['name' => 'Chocolates', 'description' => 'Barras y bombones de chocolate', 'unit_id' => 8, 'active' => true],
            ['name' => 'Caramelos', 'description' => 'Caramelos y confites', 'unit_id' => 8, 'active' => true],
            ['name' => 'Snacks', 'description' => 'Papas fritas, chizitos y otros snacks', 'unit_id' => 8, 'active' => true],
            ['name' => 'Pan de molde', 'description' => 'Panes industriales y artesanales', 'unit_id' => 8, 'active' => true],
            ['name' => 'Pan dulce', 'description' => 'Bollos, bizcochos y kekes', 'unit_id' => 8, 'active' => true],
            ['name' => 'Conservas de pescado', 'description' => 'Atún, caballa, sardinas en conserva', 'unit_id' => 8, 'active' => true],
            ['name' => 'Conservas de vegetales', 'description' => 'Choclo, arvejas, frejoles y más', 'unit_id' => 8, 'active' => true],
            ['name' => 'Salsas y condimentos', 'description' => 'Mayonesa, ketchup, mostaza', 'unit_id' => 1, 'active' => true],
            ['name' => 'Harinas', 'description' => 'Harina de trigo, maíz y otros', 'unit_id' => 2, 'active' => true],
            ['name' => 'Cereal', 'description' => 'Cereales para desayuno', 'unit_id' => 8, 'active' => true],
            ['name' => 'Detergentes', 'description' => 'Detergentes líquidos y en polvo', 'unit_id' => 8, 'active' => true],
            ['name' => 'Suavizantes', 'description' => 'Suavizantes de ropa', 'unit_id' => 1, 'active' => true],
            ['name' => 'Lavavajillas', 'description' => 'Líquidos y pastas para lavar platos', 'unit_id' => 1, 'active' => true],
            ['name' => 'Jabones de baño', 'description' => 'Jabones sólidos y líquidos', 'unit_id' => 7, 'active' => true],
            ['name' => 'Shampoo', 'description' => 'Shampoo y acondicionadores', 'unit_id' => 1, 'active' => true],
            ['name' => 'Desodorantes', 'description' => 'Desodorantes en spray y barra', 'unit_id' => 7, 'active' => true],
            ['name' => 'Papel higiénico', 'description' => 'Rollos de papel higiénico', 'unit_id' => 8, 'active' => true],
            ['name' => 'Servilletas', 'description' => 'Servilletas de papel', 'unit_id' => 8, 'active' => true],
            ['name' => 'Paños de cocina', 'description' => 'Trapos y toallas para limpieza', 'unit_id' => 8, 'active' => true],
            ['name' => 'Escobas y recogedores', 'description' => 'Utensilios de limpieza', 'unit_id' => 7, 'active' => true],
            ['name' => 'Insecticidas', 'description' => 'Sprays y líquidos para eliminar insectos', 'unit_id' => 1, 'active' => true],
            ['name' => 'Velas', 'description' => 'Velas comunes y aromáticas', 'unit_id' => 7, 'active' => true],
            ['name' => 'Encendedores', 'description' => 'Encendedores y fósforos', 'unit_id' => 7, 'active' => true],
            ['name' => 'Pilas', 'description' => 'Pilas AA, AAA, recargables', 'unit_id' => 8, 'active' => true],
            ['name' => 'Artículos escolares', 'description' => 'Cuadernos, lápices, borradores', 'unit_id' => 8, 'active' => true],
            ['name' => 'Revistas y periódicos', 'description' => 'Publicaciones impresas', 'unit_id' => 7, 'active' => true],
            ['name' => 'Cigarrillos', 'description' => 'Cigarrillos de diversas marcas', 'unit_id' => 8, 'active' => true],
            ['name' => 'Energizantes', 'description' => 'Bebidas energéticas de marca', 'unit_id' => 1, 'active' => true],
            ['name' => 'Helados', 'description' => 'Helados de crema y paletas', 'unit_id' => 8, 'active' => true],
            ['name' => 'Carne de res', 'description' => 'Cortes de carne fresca', 'unit_id' => 2, 'active' => true],
            ['name' => 'Carne de pollo', 'description' => 'Pollo entero y por piezas', 'unit_id' => 2, 'active' => true],
            ['name' => 'Embutidos', 'description' => 'Jamones, salchichas y hot dogs', 'unit_id' => 8, 'active' => true],
            ['name' => 'Pescado congelado', 'description' => 'Filetes y mariscos congelados', 'unit_id' => 2, 'active' => true],
            ['name' => 'Verduras frescas', 'description' => 'Verduras y hortalizas variadas', 'unit_id' => 2, 'active' => true],
            ['name' => 'Frutas frescas', 'description' => 'Frutas de temporada', 'unit_id' => 2, 'active' => true],
            ['name' => 'Congelados', 'description' => 'Productos congelados varios', 'unit_id' => 8, 'active' => true],
            ['name' => 'Panadería artesanal', 'description' => 'Pan artesanal fresco', 'unit_id' => 8, 'active' => true],
            ['name' => 'Pastelería', 'description' => 'Tortas, postres y dulces', 'unit_id' => 8, 'active' => true],
            ['name' => 'Confituras', 'description' => 'Mermeladas y cremas dulces', 'unit_id' => 1, 'active' => true],
            ['name' => 'Miel', 'description' => 'Miel de abeja natural', 'unit_id' => 1, 'active' => true],
            ['name' => 'Cereales integrales', 'description' => 'Avena, quinua, kiwicha', 'unit_id' => 2, 'active' => true],
            ['name' => 'Legumbres secas', 'description' => 'Frejoles, lentejas, garbanzos', 'unit_id' => 2, 'active' => true],
            ['name' => 'Condimentos naturales', 'description' => 'Orégano, pimienta, comino', 'unit_id' => 8, 'active' => true],
            ['name' => 'Sopas instantáneas', 'description' => 'Sopas y caldos de sobre', 'unit_id' => 8, 'active' => true],
            ['name' => 'Comidas enlatadas', 'description' => 'Platos preparados en conserva', 'unit_id' => 8, 'active' => true],
            ['name' => 'Productos para bebés', 'description' => 'Papillas, pañales, toallitas', 'unit_id' => 8, 'active' => true],
            ['name' => 'Cuidado dental', 'description' => 'Cepillos, pastas, enjuagues', 'unit_id' => 8, 'active' => true],
            ['name' => 'Cuidado facial', 'description' => 'Cremas y lociones faciales', 'unit_id' => 1, 'active' => true],
            ['name' => 'Cuidado corporal', 'description' => 'Cremas y aceites para la piel', 'unit_id' => 1, 'active' => true],
            ['name' => 'Protección femenina', 'description' => 'Toallas higiénicas y tampones', 'unit_id' => 8, 'active' => true],
            ['name' => 'Afeitado masculino', 'description' => 'Cuchillas, espumas y aftershave', 'unit_id' => 8, 'active' => true],
            ['name' => 'Accesorios de cocina', 'description' => 'Utensilios y artículos de cocina', 'unit_id' => 8, 'active' => true],
            ['name' => 'Artículos para mascotas', 'description' => 'Comida y accesorios para mascotas', 'unit_id' => 8, 'active' => true],
            ['name' => 'Bolsas y empaques', 'description' => 'Bolsas de plástico y papel', 'unit_id' => 8, 'active' => true],
            ['name' => 'Velas y aromatizantes', 'description' => 'Ambientadores y esencias', 'unit_id' => 1, 'active' => true],
            ['name' => 'Suplementos alimenticios', 'description' => 'Vitaminas y minerales', 'unit_id' => 8, 'active' => true],
            ['name' => 'Panetones', 'description' => 'Panetones navideños', 'unit_id' => 8, 'active' => true],
            ['name' => 'Vinos espumantes', 'description' => 'Champagne y espumantes', 'unit_id' => 1, 'active' => true],
            ['name' => 'Bebidas sin alcohol', 'description' => 'Refrescos sin alcohol', 'unit_id' => 1, 'active' => true],
            ['name' => 'Salsas picantes', 'description' => 'Ajíes y salsas picantes', 'unit_id' => 1, 'active' => true],
            ['name' => 'Gelatinas y postres', 'description' => 'Postres instantáneos', 'unit_id' => 8, 'active' => true],
            ['name' => 'Artesanías locales', 'description' => 'Productos artesanales variados', 'unit_id' => 8, 'active' => true],
            ['name' => 'Limpieza del hogar', 'description' => 'Productos generales de limpieza', 'unit_id' => 8, 'active' => true],
            ['name' => 'Ambientadores', 'description' => 'Aromas para casa y oficina', 'unit_id' => 1, 'active' => true],
            ['name' => 'Pan de hamburguesa', 'description' => 'Pan para hamburguesas y hot dogs', 'unit_id' => 8, 'active' => true],
            ['name' => 'Frutos secos', 'description' => 'Nueces, almendras y maní', 'unit_id' => 2, 'active' => true],
            ['name' => 'Productos light', 'description' => 'Alimentos bajos en azúcar o grasa', 'unit_id' => 8, 'active' => true],
            ['name' => 'Bebidas vegetales', 'description' => 'Leches de soya, almendra y avena', 'unit_id' => 1, 'active' => true],
            ['name' => 'Salsas de tomate', 'description' => 'Puré y salsa de tomate', 'unit_id' => 1, 'active' => true],
            ['name' => 'Mayonesa y aderezos', 'description' => 'Aderezos diversos', 'unit_id' => 1, 'active' => true],
            ['name' => 'Pastas de maní y chocolate', 'description' => 'Untables dulces y salados', 'unit_id' => 1, 'active' => true],
            ['name' => 'Harinas integrales', 'description' => 'Harinas de avena, arroz, quinua', 'unit_id' => 2, 'active' => true],
            ['name' => 'Cereales infantiles', 'description' => 'Cereales para bebés', 'unit_id' => 8, 'active' => true],
            ['name' => 'Verduras congeladas', 'description' => 'Mix de verduras listas para cocinar', 'unit_id' => 2, 'active' => true],
            ['name' => 'Helados artesanales', 'description' => 'Helados de crema artesanal', 'unit_id' => 8, 'active' => true],
            ['name' => 'Pan integral', 'description' => 'Panes saludables con fibra', 'unit_id' => 8, 'active' => true],
            ['name' => 'Productos sin gluten', 'description' => 'Alimentos aptos para celíacos', 'unit_id' => 8, 'active' => true],
            ['name' => 'Suplementos deportivos', 'description' => 'Proteínas y energizantes', 'unit_id' => 2, 'active' => true],
            ['name' => 'Café molido premium', 'description' => 'Café gourmet de alta calidad', 'unit_id' => 2, 'active' => true],
        ];

        Category::insert($categories);
    }
}
